### ISSUE TITLE
acquire(ports)

### ISSUE THREAD

**Issue by yegor256** [yegor256/random-port#9]
Let's make it possible to acquire a series of ports, going sequentially.

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/random-port#9` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
